apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: NodePort
  selector:
    run: load-balancer-example
  ports:
    - protocol: TCP
      port: 8080
      #targetPort: 80
      #nodePort: 32222